# Generated by Django 4.2.1 on 2023-05-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customeraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='city',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='country',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='state',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
